## Python 202

**Scenario:** Today we are going to build upon the for loops of yesterday. Who has ever got to the cash register at costco, or whole foods, seen the total and asked "how did I spend that much?". Today we have a grocery list of items and prices, but we do not have infinite money (unfortunately), so we need to have a program that will look at our grocery list and help us manage our shopping and cost.

### Learning goals:

Today we will:
 - revisit what for loop does, using a dictionary
 - use `break` to adjust loop activity
 - use nested loops to navigate a nested dictionary
 - write a robust function that will take any nested dictionary of items, costs, and print out your shopping list, stopping when the total cost gets to high, and telling you the average cost per item in your cart.

Let's revisit what a for loop does. Here we have a list of items, and a separate list of costs. We are going to write a loop to print each item, it's cost, and the total of our grocery list.

```
items = ['cheese', 'whole milk', 'kefir', 'tofu four-pack', 'kale', 'oranges', 'ham', 'ben & jerry's']
cost = [2.79, 3.42, 4.50, 12.00, 2.75, 3.64, 25.00, 5.29]
```

![groc-cart](https://images.pexels.com/photos/1389103/pexels-photo-1389103.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=750&w=1260)

### For loops:
First, let's create a for-loop that prints each item in the list with "I need to buy: " item.

In [2]:
items = ['cheese', 'whole milk', 'kefir', 'tofu four-pack', 
         'kale', 'oranges', 'ham', "ben & jerry's"]

print('I need to buy: ')
for item in items:
    print('- [] ', item)

I need to buy: 
- []  cheese
- []  whole milk
- []  kefir
- []  tofu four-pack
- []  kale
- []  oranges
- []  ham
- []  ben & jerry's


Let's make that a little nicer looking:

```
print("I need to buy: ")
for item in items:
   print(" - [ ] ", item)
```

Okay, we want to work through a dictionary, so what's one way to convert those two lists to a dictionary?

_Hint_: Check [this](https://www.w3schools.com/python/ref_func_zip.asp) documentation. 

In [23]:
cost = [2.79, 3.42, 4.50, 12.00, 2.75, 3.64, 25.00, 5.29]

In [41]:
items_cost = dict(zip(items,cost))
items_cost['avocados']

KeyError: 'avocados'

In [30]:
print('I need to buy: ')
for food,costlies in items_cost.items():
    print('- [] ',food, ": for $",costlies)

I need to buy: 
- []  cheese : for $ 2.79
- []  whole milk : for $ 3.42
- []  kefir : for $ 4.5
- []  tofu four-pack : for $ 12.0
- []  kale : for $ 2.75
- []  oranges : for $ 3.64
- []  ham : for $ 25.0
- []  ben & jerry's : for $ 5.29


In [48]:
keyes=list(items_cost.keys())
keyes

print('I need to buy: ')
for key in keyes:
    print('- [] ',key, ": for $",items_cost[key])

I need to buy: 
- []  cheese : for $ 2.79
- []  whole milk : for $ 3.42
- []  kefir : for $ 4.5
- []  tofu four-pack : for $ 12.0
- []  kale : for $ 2.75
- []  oranges : for $ 3.64
- []  ham : for $ 25.0
- []  ben & jerry's : for $ 5.29


So let's now add the total grocery bill at the end:

In [49]:
total_cost=0

print('I need to buy: ')
for key in keyes:
    print('- [] ',key, ": for $",items_cost[key])
    total_cost += items_cost[key]
print('The total cost is ',total_cost)

I need to buy: 
- []  cheese : for $ 2.79
- []  whole milk : for $ 3.42
- []  kefir : for $ 4.5
- []  tofu four-pack : for $ 12.0
- []  kale : for $ 2.75
- []  oranges : for $ 3.64
- []  ham : for $ 25.0
- []  ben & jerry's : for $ 5.29
The total cost is  59.39


Does this look reasonable?

What if you only had $25? 

How can you build it out to stop adding items when the total is over $25?

### While, break, and continue
What does a while loop look like in Python?

In [50]:
i = 1
while i < 6:
  print(i)
  i += 1

1
2
3
4
5


- What is break and continue?
- Are they different? How?
- Run the following code:

In [55]:
i = 0
while i < 6:
  i += 1
  if i == 3:
    print("foo")
    continue
  print(i)

1
2
foo
4
5
6


How does the code above work?

Now run this code:

In [56]:
i = 0
while i < 6:
  i += 1
  if i == 3:
    print("foo")
    break
  print(i)

1
2
foo


Why is the output different?

It stopped at foo, why?

We can also include `breaks` in for-loops.

What would we use to **stop** the for loop if the total reached $25?

In [61]:
total_cost = 0.0

print('I need to buy: ')
for key in keyes:
    if total_cost+items_cost[key] > 25:
        break

    print('- [] ',key, ": for $",items_cost[key])
    total_cost += items_cost[key]

print('The total cost is ',total_cost)

I need to buy: 
- []  cheese : for $ 2.79
- []  whole milk : for $ 3.42
- []  kefir : for $ 4.5
- []  tofu four-pack : for $ 12.0
The total cost is  22.71


What if we wanted to use continue and break to stop the program if an item costs more than **$10** ?

In [62]:
total_cost = 0.0

print('I need to buy: ')
for key in keyes:
    if items_cost[key] > 10:
        continue
    
    if total_cost+items_cost[key] > 25:
        break

    print('- [] ',key, ": for $",items_cost[key])
    total_cost += items_cost[key]

print('The total cost is ',total_cost)

I need to buy: 
- []  cheese : for $ 2.79
- []  whole milk : for $ 3.42
- []  kefir : for $ 4.5
- []  kale : for $ 2.75
- []  oranges : for $ 3.64
- []  ben & jerry's : for $ 5.29
The total cost is  22.39


### Nested Loops

In [63]:
numbers = [1,2,3,4,5]

for x in numbers:
  print('loop1:', x)
  for y in numbers:
    print('loop2---', y)

loop1: 1
loop2--- 1
loop2--- 2
loop2--- 3
loop2--- 4
loop2--- 5
loop1: 2
loop2--- 1
loop2--- 2
loop2--- 3
loop2--- 4
loop2--- 5
loop1: 3
loop2--- 1
loop2--- 2
loop2--- 3
loop2--- 4
loop2--- 5
loop1: 4
loop2--- 1
loop2--- 2
loop2--- 3
loop2--- 4
loop2--- 5
loop1: 5
loop2--- 1
loop2--- 2
loop2--- 3
loop2--- 4
loop2--- 5


What do you expect to see? Why?

Here's a more complicated example, what is it doing?

In [64]:
i = 2
while(i < 100):
   j = 2
   while(j <= (i/j)):
      if not(i%j): break
      j = j + 1
   if (j > i/j) : print( i, " is prime")
   i = i + 1

print ("Good bye!")

2  is prime
3  is prime
5  is prime
7  is prime
11  is prime
13  is prime
17  is prime
19  is prime
23  is prime
29  is prime
31  is prime
37  is prime
41  is prime
43  is prime
47  is prime
53  is prime
59  is prime
61  is prime
67  is prime
71  is prime
73  is prime
79  is prime
83  is prime
89  is prime
97  is prime
Good bye!


Here is a more robust shopping list of nested dictionaries:
```
shopping_dict = {'Grocieries': {'ben & jerrys': 5.29, 'cheese': 2.79,'ham': 25.0, 'kale': 2.75,'kefir': 4.5,'oranges': 3.64,'tofu four-pack': 12.0,'whole milk': 3.42},
                 'House supplies': {'toilet paper pack': 16.50, 'clorox spray': 6.43, 'kleenex': 2.50,},
                 'Pet supplies': {'Taste of the Wild': 65.20, 'squeaky toy': 4.50, 'duck feet': 8.45}}
```

write the nested for loops to print out each grocery list with its total

_Hint_

- use [this link](https://pyformat.info/#number) for help in formatting the total to two decimal places

In [65]:
shopping_dict = {'Grocieries': {'ben & jerrys': 5.29, 'cheese': 2.79,'ham': 25.0, 'kale': 2.75,'kefir': 4.5,'oranges': 3.64,'tofu four-pack': 12.0,'whole milk': 3.42},
                 'House supplies': {'toilet paper pack': 16.50, 'clorox spray': 6.43, 'kleenex': 2.50,},
                 'Pet supplies': {'Taste of the Wild': 65.20, 'squeaky toy': 4.50, 'duck feet': 8.45}}


In [68]:
total_bill = 0

for key,dept in shopping_dict.items():
    dept_total = 0
    print(key)
    
    for item,cost in dept.items():
        print('- [] -- ', item,' : ', cost)
        dept_total += cost
    
    print('The total for this department is: ',dept_total)
    total_bill += dept_total
print('The total bill is: ', total_bill)

Grocieries
- [] --  ben & jerrys  :  5.29
- [] --  cheese  :  2.79
- [] --  ham  :  25.0
- [] --  kale  :  2.75
- [] --  kefir  :  4.5
- [] --  oranges  :  3.64
- [] --  tofu four-pack  :  12.0
- [] --  whole milk  :  3.42
The total for this department is:  59.39
House supplies
- [] --  toilet paper pack  :  16.5
- [] --  clorox spray  :  6.43
- [] --  kleenex  :  2.5
The total for this department is:  25.43
Pet supplies
- [] --  Taste of the Wild  :  65.2
- [] --  squeaky toy  :  4.5
- [] --  duck feet  :  8.45
The total for this department is:  78.15
The total bill is:  162.97


In [67]:
shopping_dict.items()

dict_items([('Grocieries', {'ben & jerrys': 5.29, 'cheese': 2.79, 'ham': 25.0, 'kale': 2.75, 'kefir': 4.5, 'oranges': 3.64, 'tofu four-pack': 12.0, 'whole milk': 3.42}), ('House supplies', {'toilet paper pack': 16.5, 'clorox spray': 6.43, 'kleenex': 2.5}), ('Pet supplies', {'Taste of the Wild': 65.2, 'squeaky toy': 4.5, 'duck feet': 8.45})])

### Functions

**Built-in functions** <br>
Many useful functions are already built into Python:<br>

`print()`: print the given string or variable's value<br>
`type()`: returns the datatype of the argument<br>
`len()`: returns the length of an array<br>
`sum()`: returns the sum of the array's values<br>
`min()`: returns the smallest member of an array <br>
`max()`: returns the largest member of an array<br>


**Writing your own functions**

```
def sayHello():
  print("Hello!")
```
How do we run it?

```
sayHello()
```

Let's talk about arguments or parameters. Let's say we want to make this function more dynamic and print out whatever we want! How would we do that?
```
def shout(phrase):
  print(phrase + "!!!")
shout("oh hai")
```

What if we don't pass in an argument? What happens?
Maybe we can establish a default value for the argument in case it isn't passed in.

```
def shout(phrase = "oh hai"):
  print(phrase + "!!!")

shout()
shout("bye")
```

What if we wanted to run a function, take it's output and put it in to another function?

```
def addOne(number):
  return number + 1

def timesFive(number):
  return number * 5

numberPlusOne = addOne(1)
answer = timesFive(numberPlusOne)
print(answer)
```

What will the above code return?

Adapt your shopping list nested for-loop to be wrapped in a function you could call on any shopping list of nested dictionaries.

### Mathematical Notation and Measures of Central Tendency 

median vs mode vs mean<br>
What's the difference?


`samp_list = [1,1,1,1,2,2,2,3,3,10,44]`

How could you write a for loop to calculate the mean?

In [ ]:
samp_list = [1,1,1,1,2,2,2,3,3,10,44]




### Integration

adapt your function to do the following:
- stop the nested loop if a grocery total goes over $30
- print out the average cost of per item in your cart